### ISSUE TITLE
feat: menu message text

### ISSUE THREAD

**Issue by kitce** [grammyjs/menu#23]
Can we have something like this:

```ts
const menu = new Menu('my-menu', (context) => {
  const { session } = context;
  return `Count: ${session.count}`;
});

menu.text('Increase', (context) => {
  context.session.count++;
  context.menu.update();
});
```

So that the menu message text can be dynamic, as well as auto update it between menu navigations

Without this feature, I need to call `editMessageText` every time I want it to be refreshed, and it does not make sense for a submenu to determine what should the parent menu message text be when doing `menu.back()`

With this feature, it does not even need to put the message text in `reply()`

Instead, I suggest to have a new `replyMenu` method

```ts
- const message = `Count: ${context.session.count}`;
- context.reply(message, { reply_markup: menu });
+ context.replyMenu(menu);

**Comment by sartoshi-foot-dao** [comment]
There is indeed a minor inconvenience having to editMessageText with each back navigation.

**Comment by KnorpelSenf** [comment]
The problem is that menus work with all types of messages, not just text messages. That means that if the user sends the menu using `ctx.replyWithPhoto` in order to display the menu underneath the photo message, then calling `editMessageText` will obviously fail. There is no way for the plugin to know which type of message it is attached to.

We've discussed this a long time ago, and decided that it's the most approachable solution to leave this problem to the user, because the plugin cannot really deliver a good solution anyway. We then came up with the idea that we could let the user decide the method call, such as
```ts
const menu = new Menu('my-menu', async ctx => {
  await ctx.editMessageText(ctx.session.count)
});
```
I am not sure if this is any better than the current way of doing things. This would basically be a general handler that is always run if the menu gets updated. However, we can already do this:
```ts
async function update(ctx: MyContext, next: NextFunction) {
  await ctx.editMessageText(ctx.session.count)
  await next()
}

const menu = new Menu('my-menu')
  .text('Button', update, ctx => ctx.reply('Updated the counter!')
```
That way, `update` can be reused in all places where the menu should be updated.

I acknowledge the problem, I am just not sure if we have found the right solution yet. Please don't hesitate to drop your ideas here :)

**Comment by sartoshi-foot-dao** [comment]
Sound reasoning, fair explanation. No more questions.

**Comment by kitce** [comment]
@KnorpelSenf
Is your example a suggested solution or the current solution? 
Asking because I cannot find this usage from the documentation or the code

**Comment by kitce** [comment]
I managed to expose a set of menu message rendering functions, and import them from both parent and child menus, then do something like this whenever navigating between the menus:

```ts
// child.ts
import { renderParentMenuMessage } from './messages';

...

child.back('Back', (context, next) => {
  const message = renderParentMenuMessage(context);
  context.editTextMessage(message);
  next(); // back to parent menu
});
```

**Comment by KnorpelSenf** [comment]
Make sure to `await next()`.

**Comment by KnorpelSenf** [comment]
In fact, you should probably also await the message edit. Generally speaking, await everything that's async.
